<?php

namespace Winden\Pro\Providers;

use Winden\App\Helpers\SettingsOptions;
use Winden\App\Assets\Providers\ProvidersHelpers;

/**
 * Bricks 2.0 Data Provider
 *
 * Integrates Winden's Wizzard design tokens with Bricks Builder 2.0
 * by injecting CSS variables into Bricks Global Variables via filter hook.
 *
 * INTEGRATION METHOD:
 * -------------------
 * - Uses WordPress 'option_bricks_global_variables' filter
 * - NO database writes (clean uninstall)
 * - Variables exist only when Winden is active
 * - Dynamically injects Winden variables on each request
 *
 * PATTERN BASED ON:
 * -----------------
 * - FSEData.php - Same philosophy: MERGE, don't REPLACE
 * - Maintains independence while achieving integration
 */
class Bricks2Data
{
    public function __construct()
    {
        // Constructor is now minimal - all setup happens in run()
    }

    /**
     * Main execution method - called by the centralized system
     */
    public function run()
    {
        $settings = SettingsOptions::getWindenOptions();

        if ($settings['register_wizzard_data_in_bricks'] ?? false) {
            // Add Wizzard CSS variables to Bricks Global Variables
            add_filter('option_bricks_global_variables', [$this, 'inject_wizzard_variables'], 10);

            // Add debug output if enabled
            $this->setup_debug_output();
        }
    }

    /**
     * Inject Winden Tailwind v4 CSS variables into Bricks Builder Global Variables
     *
     * IMPORTANT: This uses WordPress option filter, NOT database writes!
     * When Winden is disabled/uninstalled, variables disappear automatically.
     *
     * HOW THIS WORKS:
     * ---------------
     * 1. Hook into WordPress 'option_bricks_global_variables' filter
     * 2. This filter is called whenever Bricks reads: get_option('bricks_global_variables')
     * 3. We parse Winden's @theme config and merge variables at runtime
     * 4. Bricks receives merged variables but NOTHING is written to database
     * 5. When Winden is disabled, the filter doesn't run = variables disappear
     *
     * WHY THIS APPROACH:
     * ------------------
     * - NO database writes = clean uninstall (no orphaned data in wp_options)
     * - Variables exist only when Winden is active
     * - Bricks reads variables via get_option() which triggers our filter
     * - Result: Dynamic injection without database pollution
     *
     * INTEGRATION STRATEGY:
     * ---------------------
     * - Merge Winden variables with existing Bricks variables
     * - Preserve existing Bricks variables (don't overwrite)
     * - Variables use Tailwind naming (e.g., color-tahiti-500)
     * - Remove old Winden vars before adding fresh ones (handles updates)
     *
     * WINDEN VARIABLE SOURCE:
     * -----------------------
     * - Variables come from Wizzard's @theme directive (Tailwind v4 config)
     * - Includes: colors (--color-*), spacing (--spacing-*), fonts (--font-*), etc.
     * - Generated by configGenerator.ts in the admin UI
     *
     * @param array $bricks_variables Existing Bricks global variables
     * @return array Merged variables array
     */
    public function inject_wizzard_variables($bricks_variables)
    {
        // Get Winden editor data (contains Wizzard config)
        $winden_editor = get_option('winden_editor', []);
        if (empty($winden_editor)) {
            return $bricks_variables; // Return original if no Winden data
        }

        // Extract Wizzard config code (contains @theme directive with CSS variables)
        $wizzard_config = $winden_editor['wizzard']['configCode'] ?? '';
        if (empty($wizzard_config)) {
            return $bricks_variables; // Return original if no config
        }

        // Parse CSS variables from @theme directive into Bricks format
        $winden_variables = $this->parse_theme_to_bricks_format($wizzard_config);
        if (empty($winden_variables)) {
            return $bricks_variables; // Return original if parsing fails
        }

        // Ensure bricks_variables is an array
        if (!is_array($bricks_variables)) {
            $bricks_variables = [];
        }

        // Build list of Winden variable IDs to exclude from Bricks variables
        $winden_variable_ids = array_column($winden_variables, 'id');

        // Remove old Winden variables (we'll re-add fresh ones)
        // Keep only variables that are NOT in the Winden list
        $bricks_only_variables = array_filter($bricks_variables, function($var) use ($winden_variable_ids) {
            return !isset($var['id']) || !in_array($var['id'], $winden_variable_ids, true);
        });

        // Merge Winden variables into Bricks variables
        $merged_variables = array_merge(array_values($bricks_only_variables), $winden_variables);

        return $merged_variables;
    }

    /**
     * Parse Winden @theme config to Bricks global variables format
     *
     * Bricks format: array of objects with 'id', 'name', and 'value' keys
     * Example: ['id' => 'color-primary', 'name' => 'Primary Color', 'value' => '#3b82f6']
     *
     * @param string $theme_config Tailwind v4 @theme directive content
     * @return array Array of Bricks global variable objects
     */
    private function parse_theme_to_bricks_format($theme_config)
    {
        // Match @theme { ... } block
        if (!preg_match('/@theme\s*\{([^}]+)\}/s', $theme_config, $matches)) {
            return [];
        }

        $theme_content = $matches[1];
        $bricks_variables = [];

        // Extract CSS custom properties (--var-name: value;)
        preg_match_all('/\s*(--[a-zA-Z0-9\-]+)\s*:\s*([^;]+);/m', $theme_content, $var_matches, PREG_SET_ORDER);

        foreach ($var_matches as $match) {
            $css_var_name = trim($match[1]); // e.g., --color-primary-500
            $css_var_value = trim($match[2]); // e.g., #3b82f6

            // Remove -- prefix to get the base variable name
            $var_name_without_prefix = ltrim($css_var_name, '-');

            // IMPORTANT: Bricks uses the 'id' as the actual CSS variable name
            // So we keep it as-is: color-tahiti-100 (NOT winden-color-tahiti-100)
            // This ensures var(--color-tahiti-100) works in CSS
            $bricks_id = $var_name_without_prefix;

            // Use the same format for name as id (e.g., color-tahiti-100)
            $bricks_name = $var_name_without_prefix;

            // Add to Bricks variables array
            $bricks_variables[] = [
                'id' => $bricks_id,              // CSS variable name: color-tahiti-100
                'name' => $bricks_name,          // Display name: color-tahiti-100
                'value' => $css_var_value,       // Value: #e6f6ff
            ];
        }

        return $bricks_variables;
    }

    /**
     * Setup debug output for development
     * Add ?winden_debug=1 to URL to enable
     */
    private function setup_debug_output()
    {
        add_action('wp_footer', function() {
            if (!isset($_GET['winden_debug']) || $_GET['winden_debug'] !== '1') {
                return;
            }

            $theme = wp_get_theme();
            $winden_editor = get_option('winden_editor', []);
            $wizzard_config = $winden_editor['wizzard']['configCode'] ?? '';
            $winden_variables = $this->parse_theme_to_bricks_format($wizzard_config);

            // Get global variables from database (what Bricks stores)
            $bricks_db_variables = get_option('bricks_global_variables', []);

            // HTML Comment Debug Output
            echo "\n\n<!-- ========================================== -->\n";
            echo "<!-- WINDEN + BRICKS DEBUG (Filter Hook Method) -->\n";
            echo "<!-- ========================================== -->\n\n";

            echo "<!-- WINDEN VARIABLES (Parsed from @theme) -->\n";
            echo "<!--\n";
            echo "Count: " . count($winden_variables) . "\n\n";
            print_r($winden_variables);
            echo "\n-->\n\n";

            echo "<!-- BRICKS DATABASE VARIABLES (From wp_options) -->\n";
            echo "<!--\n";
            echo "Count: " . count($bricks_db_variables) . "\n";
            echo "Note: These are stored in database by Bricks\n\n";
            print_r(array_slice($bricks_db_variables, 0, 5));
            echo "\n... (showing first 5)\n";
            echo "\n-->\n\n";

            echo "<!-- INTEGRATION METHOD -->\n";
            echo "<!--\n";
            echo "Method: Filter Hook (option_bricks_global_variables)\n";
            echo "Database writes: NO\n";
            echo "Variables injected: Dynamically on each request\n";
            echo "Clean uninstall: YES (no data left behind)\n";
            echo "\n-->\n\n";

            echo "<!-- ========================================== -->\n\n";

            // Console Debug Output
            ?>
            <script>
                console.group('🎨 Winden + Bricks Integration Debug (Filter Hook)');
                console.log('Theme:', <?php echo json_encode($theme->get('Name')); ?>);
                console.log('Integration Method:', 'Filter Hook (No DB writes)');
                console.log('Wizzard Config Found:', <?php echo json_encode(!empty($wizzard_config)); ?>);
                console.log('Winden Variables Parsed:', <?php echo json_encode(count($winden_variables)); ?>);
                console.log('Bricks DB Variables:', <?php echo json_encode(count($bricks_db_variables)); ?>);
                console.log('Sample Winden Variables:', <?php echo json_encode(array_slice($winden_variables, 0, 3)); ?>);
                console.groupEnd();
            </script>
            <?php
        }, 999);
    }
}
