/**
 * Tailwind CSS Class Data
 *
 * Breakpoints, variants, and utility classes for autocomplete
 * Classes are loaded dynamically from window.winden_autocomplete (generated by compiler)
 * Breakpoints and variants have sensible defaults that can be overridden at runtime
 */

import type { ClassData } from './types';

// Declare global window properties
// Note: winden_autocomplete can be an array or an object (for compatibility)
declare global {
  interface Window {
    winden_autocomplete?: string[] | Record<string | number, string>;
  }
}

// Breakpoints - can be overwritten at runtime
export let defaultBreakpoints: string[] = [
  'sm',
  'md',
  'lg',
  'xl',
  '2xl',
];

// Variants - can be extended at runtime
export let defaultVariants: string[] = [
  // Pseudo-class variants
  'hover',
  'focus',
  'focus-within',
  'focus-visible',
  'active',
  'visited',
  'target',
  'first',
  'last',
  'only',
  'odd',
  'even',
  'first-of-type',
  'last-of-type',
  'only-of-type',
  'empty',
  'disabled',
  'enabled',
  'checked',
  'indeterminate',
  'default',
  'required',
  'valid',
  'invalid',
  'in-range',
  'out-of-range',
  'placeholder-shown',
  'autofill',
  'read-only',

  // Pseudo-element variants
  'before',
  'after',
  'first-letter',
  'first-line',
  'marker',
  'selection',
  'file',
  'backdrop',
  'placeholder',

  // Media and feature queries
  'dark',
  'light',
  'motion-safe',
  'motion-reduce',
  'contrast-more',
  'contrast-less',
  'portrait',
  'landscape',
  'print',
  'ltr',
  'rtl',

  // State variants
  'open',
  'closed',

  // Group and peer variants
  'group-hover',
  'group-focus',
  'group-active',
  'group-visited',
  'peer-hover',
  'peer-focus',
  'peer-active',
  'peer-checked',
  'peer-disabled',
  'peer-invalid',

  // Aria variants
  'aria-checked',
  'aria-disabled',
  'aria-expanded',
  'aria-hidden',
  'aria-pressed',
  'aria-readonly',
  'aria-required',
  'aria-selected',

  // Data variants
  'data-active',
  'data-disabled',
  'data-loading',

  // Supports variants
  'supports-grid',
  'supports-flex',

  // Container queries
  '@sm',
  '@md',
  '@lg',
  '@xl',
  '@2xl',
];

// Classes - loaded dynamically from window.winden_autocomplete
// This starts empty and gets populated from the Winden compiler
export let defaultClasses: string[] = [];

/**
 * Get classes from window.winden_autocomplete if available
 * Handles both array and object formats for compatibility
 * Also checks window.parent (iframe sets data on parent window)
 */
function getWindenClasses(): string[] {
  if (typeof window === 'undefined') {
    return defaultClasses;
  }

  // Check both current window and parent (iframe sets data on parent)
  const autocomplete = window.winden_autocomplete ||
    (window.parent && window.parent !== window ? window.parent.winden_autocomplete : undefined);

  if (autocomplete) {
    // Handle array format
    if (Array.isArray(autocomplete)) {
      return autocomplete;
    }
    // Handle object format (used by Plain Classes)
    if (typeof autocomplete === 'object') {
      return Object.values(autocomplete);
    }
  }
  return defaultClasses;
}

// Get current class data (always returns latest values after any updates)
export function getDefaultClassData(): ClassData {
  return {
    breakpoints: defaultBreakpoints,
    variants: defaultVariants,
    classes: getWindenClasses(),
  };
}

// Alias for backward compatibility
export const defaultClassData: ClassData = {
  get breakpoints() { return defaultBreakpoints; },
  get variants() { return defaultVariants; },
  get classes() { return getWindenClasses(); },
};

/**
 * Update breakpoints (replaces existing)
 */
export function setBreakpoints(breakpoints: string[]): void {
  defaultBreakpoints = breakpoints;
}

/**
 * Add breakpoints to existing list
 */
export function addBreakpoints(breakpoints: string[]): void {
  defaultBreakpoints = [...new Set([...defaultBreakpoints, ...breakpoints])];
}

/**
 * Update variants (replaces existing)
 */
export function setVariants(variants: string[]): void {
  defaultVariants = variants;
}

/**
 * Add variants to existing list
 */
export function addVariants(variants: string[]): void {
  defaultVariants = [...new Set([...defaultVariants, ...variants])];
}

/**
 * Update classes (replaces existing)
 */
export function setClasses(classes: string[]): void {
  defaultClasses = classes;
}

/**
 * Add classes to existing list
 */
export function addClasses(classes: string[]): void {
  defaultClasses = [...new Set([...defaultClasses, ...classes])];
}

/**
 * Update all class data at once
 */
export function updateClassData(data: Partial<ClassData>): void {
  if (data.breakpoints) {
    defaultBreakpoints = data.breakpoints;
  }
  if (data.variants) {
    defaultVariants = data.variants;
  }
  if (data.classes) {
    defaultClasses = data.classes;
  }
}
